#!/bin/bash

clear
GROUPNAME=nogroup
VERSION_ID=$(cat /etc/os-release | grep "VERSION_ID")
CHECKSYSTEM=$(tail -n +2 /etc/openvpn/server.conf | grep "^username-as-common-name")
# IP=$(ip addr | grep 'inet' | grep -v inet6 | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -1)
# if [[ "$IP" = "" ]]; thenN
IP=$(wget -4qO- "http://whatismyip.akamai.com/")
#

# Color
GRAY='\033[1;33m'
GREEN='\033[0;32m'
NC='\033[0m'

echo ""
echo ""
echo "    =============== OS-32 & 64-bit =================    "
echo "    #                                              #    "
echo "    #       AUTOSCRIPT CREATED BY PIRAKIT          #    "
echo "    #    Truemoney Wallet : 096-746-2978           #    "
echo "    #               { VPN / SSH }                  #    "
echo "    #         BY : Pirakit Khawpleum               #    "
echo "    #    FB : https://m.me/pirakrit.khawplum       #    "
echo "    #                                              #    "
echo "    =============== OS-32 & 64-bit =================    "
echo "    ไอพีเซิฟ:$IP "
echo ""
  echo -e "เมนูสคริปท์ ${GRAY}PIRAKIT-VPN${NC} "
  echo ""
  echo "| 1| เพิ่มผู้ใช้ บัญชี ssh-vpn "
  echo "| 2| ตรวจสอบบัญชีผู้ใช้-อายุ "
  echo "| 3| ลบผู้ใช้บัญชี ssh-vpn "
  echo "| 4| ปิด-เปิดใช้งาน Openvpn เชื่อมได้ไม่จำกัดเครื่อง "
  if [[ "$VERSION_ID" = 'VERSION_ID="7"' || "$VERSION_ID" = 'VERSION_ID="8"' || "$VERSION_ID" = 'VERSION_ID="14.04"' ]]; then
		if [[ ! -e /etc/squid3/squid.conf ]]; then
			echo "| 5| ติดตั้ง SQUID PROXY  X "
		elif [[ -e /etc/squid3/squid.conf ]]; then
			echo "| 5| ถอนการติดตั้ง SQUID PROXY  ✔ "
		fi

	elif [[ "$VERSION_ID" = 'VERSION_ID="9"' || "$VERSION_ID" = 'VERSION_ID="16.04"' || "$VERSION_ID" = 'VERSION_ID="18.04"' ]]; then
		if [[ ! -e /etc/squid/squid.conf ]]; then
			echo "| 5| ติดตั้ง SQUID PROXY X "
		elif [[ -e /etc/squid/squid.conf ]]; then
			echo "| 5| ถอนการติดตั้ง SQUID PROXY ✔ "
		fi
	fi
  echo "|20| เปลี่ยนพอต OPENVPN เป็น 443
  echo "| 0| Update MENU SCRIPT "
  echo ""
1) # ==================================================================================================================
#!/bin/bash
#PIRAKIT-VPN
echo ""
echo ""
echo "    =============== OS-32 & 64-bit =================    "
echo "    #                                              #    "
echo "    #       AUTOSCRIPT CREATED BY PIRAKIT          #    "
echo "    #    Truemoney Wallet : 096-746-2978           #    "
echo "    #               { VPN / SSH }                  #    "
echo "    #         BY : Pirakit Khawpleum               #    "
echo "    #    FB : https://m.me/pirakrit.khawplum       #    "
echo "    #                                              #    "
echo "    =============== OS-32 & 64-bit =================    "
echo "    ไอพีเซิฟ:$IP "
echo ""
read -p "Username : " Login
read -p "Password : " Pass
read -p "Expired (hari): " masaaktif

IP=`dig +short myip.opendns.com @resolver1.opendns.com`
useradd -e `date -d "$masaaktif days" +"%Y-%m-%d"` -s /bin/false -M $Login
exp="$(chage -l $Login | grep "Account expires" | awk -F": " '{print $2}')"
echo -e "$Pass\n$Pass\n"|passwd $Login &> /dev/null
echo -e ""
echo -e "====SSH&VPN account===="
echo -e "Host: $IP" 
echo -e "Port OpenSSH: 22,80"
echo -e "Port Dropbear: 143,443"
echo -e "Squid: 8080,3128"
echo -e "Config OpenVPN (TCP 443): http://$IP:85/client.ovpn"
echo -e "Username: $Login "
echo -e "Password: $Pass"
echo -e "-----------------------------"
echo -e "ใช้งานได้จนถึง: $exp"
echo -e "============================="
echo -e "Mod by PIRAKIT-VPN"
echo -e ""
;;
2) # ==================================================================================================================
#!/bin/bash
#PIRAKIT-VPN
echo "-------------------------------"
echo "USERNAME          EXP DATE     "
echo "-------------------------------"
while read expired
do
        AKUN="$(echo $expired | cut -d: -f1)"
        ID="$(echo $expired | grep -v nobody | cut -d: -f3)"
        exp="$(chage -l $AKUN | grep "Account expires" | awk -F": " '{print $2}')"
        if [[ $ID -ge 1000 ]]; then
        printf "%-17s %2s\n" "$AKUN" "$exp"
        fi
done < /etc/passwd
JUMLAH="$(awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}' /etc/passwd | wc -l)"
echo "-------------------------------"
echo "จำนวน user : $JUMLAH user"
echo "-------------------------------"
echo -e "Mod by PIRAKIT-VPN"
echo -e ""
;;
3) # ==================================================================================================================
#!/bin/bash
#PIRAKIT-VPN

read -p " ใส่ผู้ใช้ที่จะลบ : " Nama
userdel -r $Nama
exit
;;

20 )
cd /usr/bin
#PIRAKIT-VPN
cp /etc/openvpn/1194.conf /home/1194ori.conf

sed -i 's|1194|443|' /etc/openvpn/1194.conf

service openvpn start

ufw allow 443/tcp
ufw allow 443/udp
ufw allow 444/tcp
ufw allow 444/udp

ufw enable

ufw status
ufw disable

sed -i 's/DROPBEAR_PORT=443/DROPBEAR_PORT=444/g' /etc/default/dropbear

sed -i 's/443/444/g' /etc/default/dropbear

service nginx start
service openvpn restart
service cron restart
service ssh restart
service dropbear restart
service squid3 restart
cd
;;
4) # ==================================================================================================================

clear
echo ""
echo ""
echo " =============== OS-32 & 64-bit =================    "
echo " #        AUTOSCRIPT CREATED BY PIRAKIT         #    "
echo " #      -----------About Us------------         #    "
echo " #    OS  DEBIAN 7-8-9  OS  UBUNTU 14-16-18     #    "
echo " #       Truemoney Wallet : 096-746-2978        #    "
echo " #               { VPN / SSH }                  #    "
echo " #         BY : Pirakit Khawpleum               #    "
echo " #    FB : https://m.me/pirakrit.khawplum       #    "
echo " =============== OS-32 & 64-bit =================    "
echo " ไอพีเซิฟ: $IP "
echo ""
echo " ปรับเปลี่ยนระบบของเซิฟเวอร์ "
echo ""
echo "|1| 1 ไฟล์เชื่อมต่อได้ 1 เครื่องเท่านั้น สามารถสร้างไฟล์เพิ่มได้ "
echo "|2| 1 ไฟล์เชื่อมต่อได้หลายเครื่อง แต่ต้องสร้างบัญชีเพื่อใช้เชื่อมต่อ "
echo "|3| 1 ไฟล์เชื่อมต่อได้ไม่จำกัดเครื่อง "
echo ""
read -p "เลือกหัวข้อที่ต้องการใช้งาน : " CHANGESYSTEMSERVER

case $CHANGESYSTEMSERVER in

	1)

sed -i '28d' /etc/openvpn/server.conf
sed -i '28d' /etc/openvpn/server.conf
sed -i '28d' /etc/openvpn/server.conf
sed -i '20d' /etc/openvpn/client-common.txt
echo "client-to-client" >> /etc/openvpn/server.conf
echo ""
echo " ปรับเปลี่ยนระบบของเซิฟเวอร์เป็นรูปแบบที่ 1 เรียบร้อย "
echo ""
service openvpn restart

	;;

	2)

sed -i '28d' /etc/openvpn/server.conf
sed -i '28d' /etc/openvpn/server.conf
sed -i '28d' /etc/openvpn/server.conf
sed -i '20d' /etc/openvpn/client-common.txt
if [[ "$VERSION_ID" = 'VERSION_ID="7"' ]]; then
	echo "plugin /usr/lib/openvpn/openvpn-auth-pam.so /etc/pam.d/login" >> /etc/openvpn/server.conf
	echo "client-cert-not-required" >> /etc/openvpn/server.conf
	echo "username-as-common-name" >> /etc/openvpn/server.conf
else
	echo "plugin /usr/lib/openvpn/openvpn-plugin-auth-pam.so /etc/pam.d/login" >> /etc/openvpn/server.conf
	echo "client-cert-not-required" >> /etc/openvpn/server.conf
	echo "username-as-common-name" >> /etc/openvpn/server.conf
fi
echo "auth-user-pass" >> /etc/openvpn/client-common.txt
echo ""
echo " ปรับเปลี่ยนระบบของเซิฟเวอร์เป็นรูปแบบที่ 2 เรียบร้อย "
echo ""
service openvpn restart

	;;

	3)

sed -i '28d' /etc/openvpn/server.conf
sed -i '28d' /etc/openvpn/server.conf
sed -i '28d' /etc/openvpn/server.conf
sed -i '20d' /etc/openvpn/client-common.txt
echo "duplicate-cn" >> /etc/openvpn/server.conf
echo ""
echo " ปรับเปลี่ยนระบบของเซิฟเวอร์เป็นรูปแบบที่ 3 เรียบร้อย "
echo ""
service openvpn restart

	;;
	
esac

	;;

5) # ==================================================================================================================

if [[ -e /etc/squid3/squid.conf ]]; then
	apt-get -y remove --purge squid3
	clear
echo ""
echo ""
echo " =============== OS-32 & 64-bit =================    "
echo " #        AUTOSCRIPT CREATED BY PIRAKIT         #    "
echo " #      -----------About Us------------         #    "
echo " #    OS  DEBIAN 7-8-9  OS  UBUNTU 14-16-18     #    "
echo " #       Truemoney Wallet : 096-746-2978        #    "
echo " #               { VPN / SSH }                  #    "
echo " #         BY : Pirakit Khawpleum               #    "
echo " #    FB : https://m.me/pirakrit.khawplum       #    "
echo " =============== OS-32 & 64-bit =================    "
echo " ไอพีเซิฟ: $IP "
echo ""
	echo "Squid Proxy .....Removed."
	exit
elif [[ -e /etc/squid/squid.conf ]]; then
	apt-get -y remove --purge squid
	clear
echo ""
echo ""
echo " =============== OS-32 & 64-bit =================    "
echo " #        AUTOSCRIPT CREATED BY PIRAKIT         #    "
echo " #      -----------About Us------------         #    "
echo " #    OS  DEBIAN 7-8-9  OS  UBUNTU 14-16-18     #    "
echo " #       Truemoney Wallet : 096-746-2978        #    "
echo " #               { VPN / SSH }                  #    "
echo " #         BY : Pirakit Khawpleum               #    "
echo " #    FB : https://m.me/pirakrit.khawplum       #    "
echo " =============== OS-32 & 64-bit =================    "
echo " ไอพีเซิฟ: $IP "
echo ""
	echo "Squid Proxy .....Removed."
	exit
fi

read -p "Port Proxy : " -e -i 8080 PROXY

if [[ "$VERSION_ID" = 'VERSION_ID="7"' || "$VERSION_ID" = 'VERSION_ID="8"' || "$VERSION_ID" = 'VERSION_ID="14.04"' ]]; then
	apt-get -y install squid3
	cat > /etc/squid3/squid.conf <<END
http_port $PROXY
acl localhost src 127.0.0.1/32 ::1
acl to_localhost dst 127.0.0.0/8 0.0.0.0/32 ::1
acl localnet src 10.0.0.0/8
acl localnet src 172.16.0.0/12
acl localnet src 192.168.0.0/16
acl SSL_ports port 443
acl Safe_ports port 80
acl Safe_ports port 21
acl Safe_ports port 443
acl Safe_ports port 70
acl Safe_ports port 210
acl Safe_ports port 1025-65535
acl Safe_ports port 280
acl Safe_ports port 488
acl Safe_ports port 591
acl Safe_ports port 777
acl CONNECT method CONNECT
acl SSH dst xxxxxxxxx-xxxxxxxxx/255.255.255.255
http_access allow SSH
http_access allow localnet
http_access allow localhost
http_access deny all
refresh_pattern ^ftp:           1440    20%     10080
refresh_pattern ^gopher:        1440    0%      1440
refresh_pattern -i (/cgi-bin/|\?) 0     0%      0
refresh_pattern .               0       20%     4320
END
	IP2="s/xxxxxxxxx/$IP/g";
	sed -i $IP2 /etc/squid3/squid.conf;
	if [[ "$VERSION_ID" = 'VERSION_ID="14.04"' ]]; then
		service squid3 restart
	else
		/etc/init.d/squid3 restart
	fi
	clear
echo ""
echo ""
echo " =============== OS-32 & 64-bit =================    "
echo " #        AUTOSCRIPT CREATED BY PIRAKIT         #    "
echo " #      -----------About Us------------         #    "
echo " #    OS  DEBIAN 7-8-9  OS  UBUNTU 14-16-18     #    "
echo " #       Truemoney Wallet : 096-746-2978        #    "
echo " #               { VPN / SSH }                  #    "
echo " #         BY : Pirakit Khawpleum               #    "
echo " #    FB : https://m.me/pirakrit.khawplum       #    "
echo " =============== OS-32 & 64-bit =================    "
echo " ไอพีเซิฟ: $IP "
echo ""
	echo "Squid Proxy .....Install finish."
	echo "IP Proxy : $IP"
	echo "Port Proxy : $PROXY"
	echo ""
	exit

elif [[ "$VERSION_ID" = 'VERSION_ID="9"' || "$VERSION_ID" = 'VERSION_ID="16.04"' || "$VERSION_ID" = 'VERSION_ID="18.04"' ]]; then
	apt-get -y install squid
	cat > /etc/squid/squid.conf <<END
http_port $PROXY
acl localhost src 127.0.0.1/32 ::1
acl to_localhost dst 127.0.0.0/8 0.0.0.0/32 ::1
acl localnet src 10.0.0.0/8
acl localnet src 172.16.0.0/12
acl localnet src 192.168.0.0/16
acl SSL_ports port 443
acl Safe_ports port 80
acl Safe_ports port 21
acl Safe_ports port 443
acl Safe_ports port 70
acl Safe_ports port 210
acl Safe_ports port 1025-65535
acl Safe_ports port 280
acl Safe_ports port 488
acl Safe_ports port 591
acl Safe_ports port 777
acl CONNECT method CONNECT
acl SSH dst xxxxxxxxx-xxxxxxxxx/255.255.255.255
http_access allow SSH
http_access allow localnet
http_access allow localhost
http_access deny all
refresh_pattern ^ftp:           1440    20%     10080
refresh_pattern ^gopher:        1440    0%      1440
refresh_pattern -i (/cgi-bin/|\?) 0     0%      0
refresh_pattern .               0       20%     4320
END
	IP2="s/xxxxxxxxx/$IP/g";
	sed -i $IP2 /etc/squid/squid.conf;
	/etc/init.d/squid restart
	clear
echo ""
echo ""
echo " =============== OS-32 & 64-bit =================    "
echo " #        AUTOSCRIPT CREATED BY PIRAKIT         #    "
echo " #      -----------About Us------------         #    "
echo " #    OS  DEBIAN 7-8-9  OS  UBUNTU 14-16-18     #    "
echo " #       Truemoney Wallet : 096-746-2978        #    "
echo " #               { VPN / SSH }                  #    "
echo " #         BY : Pirakit Khawpleum               #    "
echo " #    FB : https://m.me/pirakrit.khawplum       #    "
echo " =============== OS-32 & 64-bit =================    "
echo " ไอพีเซิฟ: $IP "
echo ""
	echo "Squid Proxy .....Install finish."
	echo "IP Proxy : $IP"
	echo "Port Proxy : $PROXY"
	echo ""
	exit

fi

	;;


0) # ==================================================================================================================
rm -f /usr/local/bin/menu   
wget -O /usr/local/bin/menu "https://raw.githubusercontent.com/MyGatherBk/pirakit/master/menu"
chmod +x /usr/local/bin/menu
rm -f /usr/local/bin/Auto-Delete-Client
wget -O /usr/local/bin/Auto-Delete-Client "https://raw.githubusercontent.com/MyGatherBk/PURE/master/Auto-Delete-Client"
chmod +x /usr/local/bin/Auto-Delete-Client 
menu

	;;
 * )
echo " รายการไม่ถูกต้อง "
esac
