#!/bin/bash
#Menu

echo -e "================================MENU====================================="
echo -e "* menu       : เรียกดู menu"
echo -e "* member     : ดูจำนวน user"
echo -e "* usernew     : สร้าง user ใหม่"
echo -e "* speedtest     : ทดสอบความเร็วเน็ต"
echo -e "* userd     : ลบ user"
echo -e "* trial : สร้าง user ทดลอง"
echo -e "* mutiply    : ปิด-เปิดใช้งาน Openvpn เชื่อมได้ไม่จำกัดเครื่อง "
echo -e "* proxy : ติดตั้ง SQUID PROXY "
echo -e "* 443 : ปลี่ยนพอต OPENVPN เป็น 443 "
echo -e "========================================================================="
echo -e ""
