#!/bin/bash

clear
GROUPNAME=nogroup
VERSION_ID=$(cat /etc/os-release | grep "VERSION_ID")
CHECKSYSTEM=$(tail -n +2 /etc/openvpn/server.conf | grep "^username-as-common-name")
# IP=$(ip addr | grep 'inet' | grep -v inet6 | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -1)
# if [[ "$IP" = "" ]]; thenN
IP=$(wget -4qO- "http://whatismyip.akamai.com/")
#

# Color
GRAY='\033[1;33m'
GREEN='\033[0;32m'
NC='\033[0m'

echo ""
echo ""
echo "    =============== OS-32 & 64-bit =================    "
echo "    #                                              #    "
echo "    #       AUTOSCRIPT CREATED BY PIRAKIT          #    "
echo "    #    Truemoney Wallet : 096-746-2978           #    "
echo "    #               { VPN / SSH }                  #    "
echo "    #         BY : Pirakit Khawpleum               #    "
echo "    #    FB : https://m.me/pirakrit.khawplum       #    "
echo "    #                                              #    "
echo "    =============== OS-32 & 64-bit =================    "
echo "    ไอพีเซิฟ:$IP "
echo ""
	echo -e "เมนูสคริปท์ ${GRAY}PIRAKIT-VPN${NC}"
	echo ""
  echo -e "|${GRAY}01${NC}| เพิ่มผู้ใช้ บัญชี ssh-vpn"
  echo -e "|${GRAY}02${NC}| ดูผู้ใช้ที่หมดอายุ"
  echo -e "|${GRAY}03${NC}| ลบผู้ใช้บัญชี ssh-vpn"
  echo -e "|${GRAY}20${NC}| เปลี่ยนพอต OPENVPN เป็น 443
  echo -e "|${GRAY}00${NC}| Update MENU SCRIPT"
  echo ""
1 | 01 )
#!/bin/bash
#PIRAKIT-VPN
echo ""
echo ""
echo "    =============== OS-32 & 64-bit =================    "
echo "    #                                              #    "
echo "    #       AUTOSCRIPT CREATED BY PIRAKIT          #    "
echo "    #    Truemoney Wallet : 096-746-2978           #    "
echo "    #               { VPN / SSH }                  #    "
echo "    #         BY : Pirakit Khawpleum               #    "
echo "    #    FB : https://m.me/pirakrit.khawplum       #    "
echo "    #                                              #    "
echo "    =============== OS-32 & 64-bit =================    "
echo "    ไอพีเซิฟ:$IP "
echo ""
read -p "Username : " Login
read -p "Password : " Pass
read -p "Expired (hari): " masaaktif

IP=`dig +short myip.opendns.com @resolver1.opendns.com`
useradd -e `date -d "$masaaktif days" +"%Y-%m-%d"` -s /bin/false -M $Login
exp="$(chage -l $Login | grep "Account expires" | awk -F": " '{print $2}')"
echo -e "$Pass\n$Pass\n"|passwd $Login &> /dev/null
echo -e ""
echo -e "====SSH&VPN account===="
echo -e "Host: $IP" 
echo -e "Port OpenSSH: 22,80"
echo -e "Port Dropbear: 143,443"
echo -e "Squid: 8080,3128"
echo -e "Config OpenVPN (TCP 443): http://$IP:81/client.ovpn"
echo -e "Username: $Login "
echo -e "Password: $Pass"
echo -e "-----------------------------"
echo -e "ใช้งานได้จนถึง: $exp"
echo -e "============================="
echo -e "Mod by PIRAKIT-VPN"
echo -e ""
exit
;;
3 | 03 )
#!/bin/bash
#PIRAKIT-VPN

read -p " ใส่ผู้ใช้ที่จะลบ : " Nama
userdel -r $Nama
exit
;;

20 )
cd /usr/bin
#PIRAKIT-VPN
cp /etc/openvpn/1194.conf /home/1194ori.conf

sed -i 's|1194|443|' /etc/openvpn/1194.conf

service openvpn start

ufw allow 443/tcp
ufw allow 443/udp
ufw allow 444/tcp
ufw allow 444/udp

ufw enable

ufw status
ufw disable

sed -i 's/DROPBEAR_PORT=443/DROPBEAR_PORT=444/g' /etc/default/dropbear

sed -i 's/443/444/g' /etc/default/dropbear

service nginx start
service openvpn restart
service cron restart
service ssh restart
service dropbear restart
service squid3 restart
cd
;;
00 )
rm -f /usr/local/bin/menu   
wget -O /usr/local/bin/menu "https://raw.githubusercontent.com/MyGatherBk/pirakit/master/menu"
chmod +x /usr/local/bin/menu
menu
;;
 * )
echo " รายการไม่ถูกต้อง "
esac
